### ISSUE TITLE
Haptic Pancake Hotfix (v0.5.3) 's identify button doesn't seem to work correctly for TundraTracker. But latest source works correctly.

### ISSUE THREAD

**Issue by xlwnya** [Z4urce/VRC-Haptic-Pancake#17]
I tried latest release (v0.5.3) binary and I found it's identify button doesn't vibrate the tundra tracker.

I don't know why because I tried to run Haptic Pancake from source (2024-08-20) before and it vibrate the tundra tracker correctly.

Is some regression happened to release?

I tried latest commit (011bff28b68d336e4789825fe75800894297c968) and it also works correctly.

v0.5.3 vibrates the tundra tracker 500us
![indentify_pulse_v0 5 3_500us](https://github.com/user-attachments/assets/e34dcee0-a5fc-4e98-8da0-238fefe44ba2)

latest source vibrates the tundra tracker 500ms
![indentify_pulse_latest_source_500ms](https://github.com/user-attachments/assets/d8f962b0-7ba3-4dc4-8a98-6fb4f824b792)

**Comment by xlwnya** [comment]
Here is diff of my local source. (I use Japanese version of Windors and this adhoc patch fixes character set problem (My Windows can't display the "⚫" in console)
And I think this diff is not related to the problem of TundraTracker support.
```
 BridgeApp/app_gui.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/BridgeApp/app_gui.py b/BridgeApp/app_gui.py
index aeadc12..3aac17b 100644
--- a/BridgeApp/app_gui.py
+++ b/BridgeApp/app_gui.py
@@ -101,7 +101,7 @@ class GUIRenderer:
         return sg.Text('', font=('AnyFont', 1), auto_size_text=True)
 
     def tracker_row(self, tracker_id, tracker_serial, tracker_model):
-        string = f"⚫ {tracker_serial} {tracker_model}"
+        string = f"{tracker_serial} {tracker_model}"
 
         dev_config = self.config.get_tracker_config(tracker_serial)
         address = dev_config.address
```

**Comment by digitalf0x** [comment]
I'm not sure, but I think there might be something missing from the release build uploaded to GitHub.  A friend I was helping also had the issue of the wrong pulse length.

If you can capture Python's console output on Windows, you can look for `Using 4.0 ms pulse limit workaround for […]` - if that's not there, the code isn't working either.

The commit in question is [[Update] Support Tundra Tracker with timing quirks](https://github.com/Z4urce/VRC-Haptic-Pancake/commit/8f5b5ba26c8eb711b4ec529e0dc791275b489a1b ).

**Comment by xlwnya** [comment]
New release "Haptic Pancake (v0.6.0a)" vibrate the tundra tracker correctly!
It's fixed.
Thank you!
